# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Deploy para Fly.io

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Permite rodar o deploy manualmente via botão no GitHub

jobs:
  deploy:
    name: Deploy no Fly.io
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy para Fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}


